### ISSUE TITLE
Polacode doesn't work after VSCode 1.47, replace it with CodeSnap?

### ISSUE THREAD

**Issue by bluedasher13** [Gydunhn/VSC-Essentials#2]
As we know, [Polacode](https://github.com/octref/polacode) doesn't work on VSCode 1.47.0 and later version (#https://github.com/octref/polacode/issues/143).

However, [CodeSnap](https://github.com/kufii/CodeSnap) does works, would you replace Polacode with CodeSnap?

**Comment by Gydunhn** [comment]
Hi, sorry for the delay in answering you, currently I am not actively using VSC as I used to, I checked the problem you are talking about, there is a version of MrRefactorin ([Polacode (fixed edition)](https://github.com/MrRefactoring/polacode)) that has the integrated fix, but I don't know if it will be maintained, so the change to [CodeSnap](https://github.com/kufii/CodeSnap) seems correct. (fixed with [this](https://github.com/Gydunhn/VSC-Essentials/releases/tag/polacodeRemoval) Release)
